[project]
name = "bert-summarizer"
version = "0.0.0"
description = "Text Summarization Library based on transformers"
license = "MIT"
authors = [
  {name = "k-tahiro", email = "tahiro.k.ad@gmail.com"}
]
readme = "README.md"
urls = {Homepage = "https://github.com/k-tahiro/bert-summarizer"}
keywords = ["BERT", "Text Summarization"]
requires-python = ">=3.8,<3.13"

dependencies = [
  "ginza>=4.0.5,<5.0.0",
  "transformers[ja,torch]>=4.0.0",
]

[project.optional-dependencies]
dev = [
  "tox",
  "pytest",
  "pytest-cov",
  "pre-commit",
  "mypy",
  "black",
]
onmt = [
  "OpenNMT-py>=2.0.1",
]

[tool.black]
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true

[tool.isort]
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
