[tool.poetry]
name = "bert-summarizer"
version = "0.0.0"
description = "Text Summarization Library based on transformers"
license = "MIT"
authors = ["k-tahiro <tahiro.k.ad@gmail.com>"]
readme = "README.md"
repository = "https://github.com/k-tahiro/bert-summarizer"
keywords = ["BERT", "Text Summarization"]

[tool.poetry-dynamic-versioning]
enable = true

[tool.poetry.dependencies]
python = ">=3.6,<3.9"
transformers = ">=4.0.0"
torch = ">=1.0"
fugashi = ">=1.0"
ipadic = ">=1.0.0,<2.0"
unidic_lite = ">=1.0.7"
unidic = ">=1.0.2"
ginza = ">=4.0.5"

[tool.poetry.dev-dependencies]
tox = "*"
coverage = "*"
isort = "^5.7.0"

[tool.isort]
line_length = 160

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
